New script to check if a server is vulnerable to CVE-2020-25648
tlsfuzzer/tlsfuzzer pull request #741
Opened 2021-03-01 20:23 UTC by inikolcev

### Description

Add a new script that tests if a server is vulnerable to CVE-2020-25648. 
### Motivation and Context

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [x] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741)

2021-03-02 12:24 UTC, tomato42 requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741)* status: all files reviewed, 6 unresolved discussions (waiting on @inikolcev)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmpn8jDrMOcEDzBUQU:-MUmpn8kADOyeolbbeti:b-90h31q) (no related file):*
all tls 1.3 tests have `tls13` in the name

---
*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmqKr5BtquAtSmNiyd:-MUmqKr5BtquAtSmNiye:brt21hr) (no related file):*
while we use this script for CVE-2020-25648 (and should document it as such), what it's doing is sending additional CCS messages, so I wonder if it wouldn't be better to name it like `test-tls13-multiple-ccs-messages.py` or something...

---
___
*[scripts/test-cve-2020-25648.py, line 163 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmq6gmAL2kgZiJvz5f:-MUmq6gmAL2kgZiJvz5g:bm5f7gk) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0093b8427031527c77fd31e672a6dcaee88245c9/scripts/test-cve-2020-25648.py#L163)):*
> ```Python
>     node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
>     node = node.add_child(TCPBufferingEnable())
>     for i in range(10):
> ```

wasn't the fix about rejecting the second CCS? then I think we should test the boundary condition, that one CCS is accepted but two are rejected

also placing the second CCS later, after client Certificate

fragmentation, like described in #207 may also be an interesting addition
___
*[scripts/test-cve-2020-25648.py, line 176 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmsy8D-U1V924vF9sh:-MUmsy8D-U1V924vF9si:bds4w38) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0093b8427031527c77fd31e672a6dcaee88245c9/scripts/test-cve-2020-25648.py#L176)):*
> ```Python
>                           AlertDescription.unexpected_message))
>     node = node.add_child(ExpectClose())
>     conversations["Multiple CCS Messages in one TCP packet"] = conversation
> ```

multiple CCS messages in single TLS record would also be nice to test
___
*[tests/tlslite-ng.json, line 70 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmt9yO5q0FgGTgEeff:-MUmt9yO5q0FgGTgEefg:b9mi6r2) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0093b8427031527c77fd31e672a6dcaee88245c9/tests/tlslite-ng.json#L70)):*
> ```JSON
>          {"name" : "test-cve-2016-6309.py"},
>          {"name" : "test-cve-2016-7054.py"},
>          {"name" : "test-cve-2020-25648.py"},
> ```

tlslite-ng accepts multiple CCS messages so the test like this will fail
___
*[tests/tlslite-ng-random-subset.json, line 69 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUmtPtTC66SOfqVM5zd:-MUmtPtU0MJoD4VNN3FR:b-2guby3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0093b8427031527c77fd31e672a6dcaee88245c9/tests/tlslite-ng-random-subset.json#L69)):*
> ```JSON
>          {"name" : "test-cve-2016-6309.py"},
>          {"name" : "test-cve-2016-7054.py"},
>          {"name" : "test-cve-2020-25648.py"},
> ```

same here


<!-- Sent from Reviewable.io -->

2021-03-03 14:58 UTC, inikolcev commented
> all tls 1.3 tests have `tls13` in the name

> while we use this script for CVE-2020-25648 (and should document it as such), what it's doing is sending additional CCS messages, so I wonder if it wouldn't be better to name it like `test-tls13-multiple-ccs-messages.py` or something...

Right, I was kinda 50-50 about test-cve or test-tls13-. It is changed now.


> wasn't the fix about rejecting the second CCS? then I think we should test the boundary condition, that one CCS is accepted but two are rejected
> 

Right, we are sending 2 by default now, but there is the --ccs switch if you want to send more. Also there is a separate Sanity conversation where we send 1 CCS

> also placing the second CCS later, after client Certificate

We don't actually need to send a client cert right? I sent the second one just before the client finished message. I'll update the script if we need to send the cert.


> multiple CCS messages in single TLS record would also be nice to test

Added a conversation for that

> tlslite-ng accepts multiple CCS messages so the test like this will fail

Right, excluded the ones that are expect them to fail.

2021-03-03 15:23 UTC, tomato42 requested changes
> We don't actually need to send a client cert right? I sent the second one just before the client finished message. I'll update the script if we need to send the cert.

that depends on server configuration, the only time we can send a Certificate is when server sent CertificateRequest

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-:-MUsd_cd6sgoayECNqwU:bflqg1r)* status: all files reviewed, 3 unresolved discussions (waiting on @inikolcev)

___
*[tests/tlslite-ng.json, line 297 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUsehGP1_kXMPlgH1qf:-MUsehGQC4W_57Y5SF62:b-kpaxjo) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/32051aa75d61198610cad708bd07b38aaf177e57/tests/tlslite-ng.json#L297)):*
> ```JSON
>          {"name" : "test-tls13-legacy-version.py"},
>          {"name" : "test-tls13-multiple-ccs-messages.py",
>           "arguments" : ["-e", "second CCS before client finished",
> ```

shouldn't those be `-x` rather than `-e` options?
___
*[tests/tlslite-ng-random-subset.json, line 299 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUsemT45sslf3GksPJa:-MUsemT45sslf3GksPJb:b-2guby3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/32051aa75d61198610cad708bd07b38aaf177e57/tests/tlslite-ng-random-subset.json#L299)):*
> ```JSON
>           "arguments" : ["-e", "second CCS before client finished",
>                          "-e", "multiple CCS Messages in one TCP packet",
>                          "-e", "CH and multiple CCS Messages in one TCP packet"],
> ```

same here
___
*[scripts/test-tls13-multiple-ccs-messages.py, line 330 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741#-MUsfC6n1-cUkFBdDH8u:-MUsfC6n1-cUkFBdDH8v:b-2wvaqf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/32051aa75d61198610cad708bd07b38aaf177e57/scripts/test-tls13-multiple-ccs-messages.py#L330)):*
> ```Python
>     node = node.add_child(ExpectCertificateVerify())
>     node = node.add_child(ExpectFinished())
>     node = node.add_child(ExpectNoMessage(timeout=6))
> ```

why the NoMessage here?


<!-- Sent from Reviewable.io -->

2021-03-04 11:55 UTC, tomato42 commented
also, please rebase on top of master, I should have fixed the py3.7 failures

2021-03-19 17:22 UTC, tomato42 approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/741)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @inikolcev)



<!-- Sent from Reviewable.io -->

2021-03-19 17:23 UTC, merged

2021-03-19 17:24 UTC, tomato42 commented
thanks for the script!