ffdhe: add option to set default socket timeout
tlsfuzzer/tlsfuzzer pull request #782
Opened 2021-12-20 13:20 UTC by ueno

The tests using ffdhe8192 take long time on some CI setup (e.g., with
software emulated GMP) and cause intermittent timeout.  This adds -t
option to control the timeout value from the test invocation.

Signed-off-by: Daiki Ueno <dueno@redhat.com>

### Description

### Motivation and Context

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [x] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

Confirmed at:
https://gitlab.com/dueno/gnutls/-/jobs/1903136178

2021-12-20 13:23 UTC, tomato42 requested changes

2021-12-20 13:23 UTC, tomato42 commented on scripts/test-ffdhe-expected-params.py
> +import socket
unused import

2021-12-20 13:23 UTC, tomato42 commented on scripts/test-ffdhe-expected-params.py
> +    timeout = 1.0
shouldn't we keep the default at 5 seconds?

2021-12-20 13:23 UTC, tomato42 commented on scripts/test-ffdhe-negotiation.py
> +import socket
unused import

2021-12-20 13:23 UTC, tomato42 commented on scripts/test-ffdhe-negotiation.py
> +    timeout = 1.0
same here, probably 5s would be better

2021-12-20 15:44 UTC, ueno commented
@tomato42 I've addressed the issues; could you take a second look?

2021-12-20 17:29 UTC, tomato42 approved these changes

2021-12-20 17:30 UTC, tomato42 commented
Looks good but will need to fix py3.3 before merge

2022-01-05 14:09 UTC, tomato42 commented
@ueno I've updated the CI config, it should pass now, could you rebase?

2022-01-05 19:31 UTC, tomato42 commented
@ueno Now it's fixed: https://github.com/tlsfuzzer/tlsfuzzer/actions/runs/1660011256

2022-02-04 17:46 UTC, ueno commented
@tomato42 what else should I do to get this merged?

2022-02-08 20:09 UTC, tomato42 commented
*sigh* 3.9 has a new release (3.9.10) so we'll need another rebase after #787 is merged...
That 3.3 failure looks like a python crash, not sure what causes it

2022-02-09 15:05 UTC, tomato42 commented
It looks like the py3.3 crash was caused by gmpy or gmpy2, I've disabled them for now on that python version, please rebase

2022-02-09 16:52 UTC, tomato42 approved these changes

2022-02-09 16:52 UTC, merged

2022-02-09 16:52 UTC, tomato42 commented
thanks! and sorry for the CI failures