EMS support followup
tlsfuzzer/tlsfuzzer pull request #828
Opened 2023-07-19 14:25 UTC by ueno

### Description

This is a follow-up of #816, to support EMS in more scripts.

### Motivation and Context

Those scripts are used in testing GnuTLS, and without this PR, they fails in FIPS mode after the recent enforcement of EMS: https://gitlab.com/gnutls/gnutls/-/merge_requests/1752

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

2023-07-20 09:40 UTC, ueno commented
*[`scripts/test-record-size-limit.py` line 1197 at r8](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mbUzM4JwAXaf6ALqT:-N_meac00VUeEpL6DLgJ:b-l7ktd5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/33117b100dfc2dc760267dd8e220b5c89fa47046/scripts/test-record-size-limit.py#L1197)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

TLS 1.3, not needed
</blockquote></details>

This test advertises both TLS 1.3 and 1.2; can we assume TLS 1.3 is always negotiated?


<!-- Sent from Reviewable.io -->

2023-07-20 10:03 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828)* status: all files reviewed, 66 unresolved discussions (waiting on @ueno)

___
*[`scripts/test-record-size-limit.py` line 1197 at r8](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mbUzM4JwAXaf6ALqT:-N_mkEWh4pFfSpF1bYhk:b-jc1j7b) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/33117b100dfc2dc760267dd8e220b5c89fa47046/scripts/test-record-size-limit.py#L1197)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

This test advertises both TLS 1.3 and 1.2; can we assume TLS 1.3 is always negotiated?
</blockquote></details>

Since it expects EncryptedExtensions, yes, it will fail if anything but TLS 1.3 is negotiated


<!-- Sent from Reviewable.io -->

2023-07-21 08:01 UTC, ueno reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828)* status: 0 of 10 files reviewed, 66 unresolved discussions (waiting on @tomato42)

___
*[`scripts/test-certificate-verify-malformed-sig.py` line 75 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mYsau62zPRkLWwvLR:-N_rSsjp4V8qNTd6CAet:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/91fd3f09aa888daefd751b8dae0f9c745b957c02/scripts/test-certificate-verify-malformed-sig.py#L75)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

long option missing
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-signatures.py` line 66 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWEUYA4vOPWJPglmr:-N_rSF7g9l-rpJ8lDvFD:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/401b8b235134aac7a672f37ad8aa28aac3b9aef6/scripts/test-dhe-rsa-key-exchange-signatures.py#L66)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`"ems"` missing in long options
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-signatures.py` line 118 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWKKt1aGxdVV4S4O8:-N_rSHW99pE0wSBEG1OH:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/401b8b235134aac7a672f37ad8aa28aac3b9aef6/scripts/test-dhe-rsa-key-exchange-signatures.py#L118)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

when extensions are specified in `ExpectServerHello`, they need to list all the ones we expect, in this case, EMS too so the list of expected needs to be built dynamically
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-signatures.py` line 158 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWVZS-wBr9yUjBTGp:-N_rSIX65ia7M724-eN1:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/401b8b235134aac7a672f37ad8aa28aac3b9aef6/scripts/test-dhe-rsa-key-exchange-signatures.py#L158)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 73 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWebo8-U4jYozyXIM:-N_rSJ8d3qAccxRiCKzq:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L73)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

long option missing
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 122 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWhCIEh8wCeYPB3kX:-N_rSJuYE-jZxu20wFip:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L122)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

ServerHello extensions need conditional EMS too
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 159 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWlJ_13P-OwV4_8tk:-N_rSKVgAEOAqUNfJa-y:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L159)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional ems too
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 190 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWq-A8-NDQGmzPSCW:-N_rSL4eD_riG5vUyOcW:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L190)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional EMS
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 221 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWvZU4pW9WUl449k9:-N_rSLgC9MEMlryBbI20:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L221)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional EMS
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 251 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mWzdEEpe9hZxcUSPN:-N_rSMP2Cx69OQwM3K_0:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L251)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional EMS
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 283 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mX-SZ05FfvB2G0HHG:-N_rSNAj5gujg8CWYCgL:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L283)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional EMS
</blockquote></details>

Done.
___
*[`scripts/test-dhe-rsa-key-exchange-with-bad-messages.py` line 315 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mX06Q818kPtAiM92C:-N_rSNj3-h7nf_MyWI1I:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/dae608d56fd38c0538d2d8433a5bd2eb62427b2b/scripts/test-dhe-rsa-key-exchange-with-bad-messages.py#L315)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

needs conditional EMS
</blockquote></details>

Done.
___
*[`scripts/test-export-ciphers-rejected.py` line 67 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mX5kE96UbeGid9Gg1:-N_rSOD2As7jP1LW-0ef:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/b97141995b6a474fc4af9929a56155b65f0e1649/scripts/test-export-ciphers-rejected.py#L67)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

long option missing
</blockquote></details>

Done.
___
*[`scripts/test-export-ciphers-rejected.py` line 222 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mXNMX7zyKNLnnnrUU:-N_rSOrvBAEdIQvkLxhZ:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/b97141995b6a474fc4af9929a56155b65f0e1649/scripts/test-export-ciphers-rejected.py#L222)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why no EMS here?
</blockquote></details>

Done.
___
*[`scripts/test-ffdhe-negotiation.py` line 75 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mZBMW5QIZoA3Wy6Aj:-N_rSPWICXnLk0HvoZsM:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6a06f295b6bdf831a766eef0193220585e9a33b/scripts/test-ffdhe-negotiation.py#L75)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

long option missing
</blockquote></details>

Done.
___
*[`scripts/test-ffdhe-negotiation.py` line 126 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mZFgEEuaQdg7KpV-l:-N_rSQ476ZZNvosxTHzZ:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6a06f295b6bdf831a766eef0193220585e9a33b/scripts/test-ffdhe-negotiation.py#L126)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

EMS needs to be added conditionally here too
</blockquote></details>

Done.
___
*[`scripts/test-ffdhe- [...]

2023-07-21 12:05 UTC, tomato42 requested changes
> Reviewed 2 of 10 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828)* status: all files reviewed, 1 unresolved discussion (waiting on @ueno)

___
*[`scripts/test-record-size-limit.py` line 1158 at r8](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828#-N_mbPHYAcqvBMWvCG0y:-N_sGQ5C6xUgDButUU3_:bkiv0nx) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/33117b100dfc2dc760267dd8e220b5c89fa47046/scripts/test-record-size-limit.py#L1158)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

those are different `ext` objects,
```
ext = {ExtensionType.renegotiation\_info: None}
```
missing before `if ems:`


<!-- Sent from Reviewable.io -->

2023-07-21 13:25 UTC, tomato42 approved these changes
> Reviewed 1 of 3 files at r20, 1 of 1 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/828)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ueno)



<!-- Sent from Reviewable.io -->

2023-07-21 13:58 UTC, merged

2023-07-21 13:59 UTC, tomato42 commented
@ueno thanks for the code!