TLS-level gatherer for Minerva analysis.
tlsfuzzer/tlsfuzzer pull request #885
Opened 2023-11-09 12:54 UTC by GeorgePantelakis

A script was created to gather, extract, and analyze data for the Minerva attack and detect side channels for ECDSA curves. The script is working on the TLS level and can test any server that accepts TLSv1.3.

2023-11-10 18:43 UTC, tomato42 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: all files reviewed, 20 unresolved discussions (waiting on @GeorgePantelakis)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuU81aCALx_k9lpCkA:-NiuU81aCALx_k9lpCkB:bru5z55) (no related file):*
The script tests Minerva only in TLS 1.3 servers, so it should be named `test-tls13-minerva.py`
I think we can also drop the "ecdsa", as the approach for EdDSA will be the same, and we can use the same data collection for both ECDSA and ECDH (in the future).

___
*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuX9er8O9Wppiqv7dd:-NiuX9et3KSw9YTjxR5K:b-nifgdi) (no related file):*
When I run it against tlslite-ng I'm getting an error:
```
[Decimal('1699641567.684276569')]  
[Decimal('1699641567.688228384'), Decimal('1699641567.692023192')]  
Done:   1.06%, elapsed:  0.00s, speed: 3.34MiB/s, avg speed: 3.34MiB/s, remaining:  0.06s, ETA: 19:39:31 10-11-2023       
Traceback (most recent call last):  
 File "/home/hkario/dev/tlsfuzzer/scripts/test-minerva-ecdsa.py", line 449, in <module>
...
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 595, in add_timing  
   self._flush_to_files()  
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 615, in _flush_to_files  
   self._write_pkt_header()  
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 770, in _write_pkt_header  
   raise ValueError("For every client query we need a response "  
ValueError: For every client query we need a response (try FIN as server response)
```

some code missing?

___
___
*[`scripts/test-minerva-ecdsa.py` line 64 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuREnK6yUeSw-quSpw:-NiuREnLEc3stA9Z8Wxx:b-hvp421) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L64)):*
> ```Python
>     print(" -C ciph          Use specified ciphersuite. Either numerical value or")
>     print("                  IETF name.")
>     print(" -c curve         The curve to use to run the test. Choose from P-256,")
> ```

single letter options are reserved for options that are shared by many scripts, this option is very Minerva specific
___
*[`scripts/test-minerva-ecdsa.py` line 66 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuRNocAYNQSQW0aEOS:-NiuRNocAYNQSQW0aEOT:b-lms3wk) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L66)):*
> ```Python
>     print(" -c curve         The curve to use to run the test. Choose from P-256,")
>     print("                  P-384 or P-521. Default P-256.")
>     print(" -s samples       Number of samples (connections) to be gathered and extracted.")
> ```

same here, and for timing tests we already use `--repeat`
___
*[`scripts/test-minerva-ecdsa.py` line 69 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuRcM9-HcK5pVCMJDl:-NiuRcM9-HcK5pVCMJDm:bp1qnnz) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L69)):*
> ```Python
>     print("                  Default 100,000")
>     print(" --data-out file  The file to write the data signed in binary form.")
>     print("                  It will override any existing file. Default data.bin.")
> ```

I see no reason to have it configurable, it's an implementation detail, the script needs to create a new, fresh, empty directory for every run, so there shouldn't be an issue with overwriting data
___
*[`scripts/test-minerva-ecdsa.py` line 71 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuRwQGCwPbzLRqrp6i:-NiuRwQGCwPbzLRqrp6j:b-2guby3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L71)):*
> ```Python
>     print("                  It will override any existing file. Default data.bin.")
>     print(" --sigs-out file  The file to write the signatures in binary form.")
>     print("                  It will override any existing file. Default sigs.bin.")
> ```

same here
___
*[`scripts/test-minerva-ecdsa.py` line 73 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuS7wUEdryFWM8IlHC:-NiuS7wUEdryFWM8IlHD:bhis6bj) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L73)):*
> ```Python
>     print("                  It will override any existing file. Default sigs.bin.")
>     print(" --priv-key file  The file that contains the ecdsa private key. This is")
>     print("                  optional and if provided will enable also extraction")
> ```

optional for running timing analysis
___
*[`scripts/test-minerva-ecdsa.py` line 75 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuSBsIBJrDj2D6vSJL:-NiuSBsIBJrDj2D6vSJM:b-mcgyzl) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L75)):*
> ```Python
>     print("                  optional and if provided will enable also extraction")
>     print("                  of measurements.csv on top of data collection.")
>     print(" --clock-frequency freq Assume that the times in the file are not")
> ```

the times are from the tcpdump, they are in nanoseconds, there's no need for specifying them
___
*[`scripts/test-minerva-ecdsa.py` line 83 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuSO-dD1aVB_JUgGeW:-NiuSO-dD1aVB_JUgGeX:b5n3wcp) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L83)):*
> ```Python
>     print("                  is enabled.")
>     print(" --analyze        Enables analysis of extracted data. This option is")
>     print("                  only relevant if extraction of data is enabled.")
> ```

if the interface for capture was provided, the analysis should run, no need to specify it on the command line
___
*[`scripts/test-minerva-ecdsa.py` line 85 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuVBAT5vGsNkNTaNGK:-NiuVBAT5vGsNkNTaNGL:byy11m0) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L85)):*
> ```Python
>     print("                  only relevant if extraction of data is enabled.")
>     print(" --verbose        Print's a more verbose output.")
>     print(" --help           this message")
> ```

having support for `--status-delay=30` and `--status-newline` would be nice or running the script in CI
___
*[`scripts/test-minerva-ecdsa.py` line 109 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuUq629R6sa9fFjjV0:-NiuUq629R6sa9fFjjV1:b-wjmo7a) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L109)):*
> ```Python
> 
>     argv = sys.argv[1:]
>     opts, args = getopt.getopt(argv, "h:p:o:e:x:X:n:C:c:s:", ["help", "data-out=",
> ```

`i:` missing
___
*[`scripts/test-minerva-ecdsa.py` line 328 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuPvX8A85j3gLeVwl9:-NiuPvX8A85j3gLeVwlA:b-i20r64) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L328)):*
> ```Python
>                 failed.append(c_name)
> 
>     print("""Gatherer to check is a server is valnurable to Minerva attack
> ```

Well, it does everything, so I think we can call it "Test script to check..."
___
*[`scripts/test-minerva-ecdsa.py` line 333 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuQX96BxmHKMsGv83P:-NiuQX96BxmHKMsGv83Q:b1fvaza) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L333)):*
> ```Pyth [...]

2023-11-10 18:44 UTC, tomato42 commented
and please add the minerva script to json files

2023-11-14 13:53 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: all files reviewed, 21 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`scripts/test-minerva-ecdsa.py` line 363 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjD5gIV82pZx75vnquI:-NjD5gIV82pZx75vnquJ:b-avo0tl) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L363)):*
> ```Python
>         tests = [('generic', None)]
> 
>         timing_runner = TimingRunner("minerva_{0}".format(curve),
> ```

in general, for the timing test results we include the full name of the script and the version of the script


<!-- Sent from Reviewable.io -->

2023-11-14 18:30 UTC, tomato42 commented
also, am I missing something, or is the analysis for the `measurements-invert.csv` not executed?

2023-11-16 15:58 UTC, GeorgePantelakis commented
> also, am I missing something, or is the analysis for the `measurements-invert.csv` not executed?

Yes, you are correct it is not analyzed because I have hardcoded the filename to be "measurements.csv" and in the manual analysis, I just combined them to be called that. I should fix that but since it is a command line change it will be quite big (due to mocking tests). So this will be done perhaps in another PR or in this one later (whichever works better for you)

2023-11-16 16:34 UTC, tomato42 commented
> I should fix that but since it is a command line change it will be quite big (due to mocking tests). So this will be done perhaps in another PR or in this one later (whichever works better for you)

if you think it will be a large, then yeah, doing it in a separate PR is likely a good idea; please file a ticket to do that and assign yourself to it

2023-11-21 18:38 UTC, tomato42 commented
```
test-tls13-minerva.py:stdout:Running timing tests...
test-tls13-minerva.py:stdout:WARNING: Timing tests should run with root privileges,as it improves accuracy and might be needed for tcpdump.
test-tls13-minerva.py:stdout:tcpdump: lo: You don't have permission to capture on that device
test-tls13-minerva.py:stdout:
test-tls13-minerva.py:stdout:(socket: Operation not permitted)
test-tls13-minerva.py:stdout:
test-tls13-minerva.py:stdout:tcpdump could not be started. Do you have the correct permissions?
ERROR:__main__:test-tls13-minerva.py:failure:1.22s:1
```
we probably shouldn't run real packet capture in the `tlslite-ng-random-subset.json` configuration

2023-11-22 14:00 UTC, tomato42 requested changes
> Reviewed 2 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: all files reviewed, 11 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tests/tlslite-ng.json` line 608 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjrHr6PCSbVHzTHnihk:-NjrHr6PCSbVHzTHnihl:bfy96as) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/tests/tlslite-ng.json#L608)):*
> ```JSON
>          {"name": "test-tls13-ecdsa-support.py"},
>          {"name" : "test-tls13-minerva.py",
>           "arguments": ["--curv", "P-256",
> ```

typo, `e` missing
___
*[`tlsfuzzer/analysis.py` line 1702 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjoIkP8DcAtk0MzqIvq:-NjoIkP9Axb6ElbsINwl:b-ens5x8) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/tlsfuzzer/analysis.py#L1702)):*
> ```Python
>                         .format(k_size, passed, total, statistic, pvalue)
>                 )
>                 pvalue = results
> ```

I don't think this line should be here
___
*[`tlsfuzzer/analysis.py` line 1704 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjrIHwj5oXbe_4BObd4:-NjrIHwj5oXbe_4BObd5:b-326z84) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/tlsfuzzer/analysis.py#L1704)):*
> ```Python
>                 pvalue = results
> 
>                 if pvalue < self.alpha:
> ```

missing https://en.wikipedia.org/wiki/Bonferroni_correction ?
___
*[`tlsfuzzer/expect.py` line 1041 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuPGdcDbaqy6IuZI-N:-NjrIZJZ0ySDbfxQfGhX:b2dvh5x) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/tlsfuzzer/expect.py#L1041)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

doc string for this missing, also shouldn't that be `hash_file` not `data_file`?
</blockquote></details>

that's a better doc text, but having every parameter described precisely is really needed here: this is user-facing documentation
___
*[`scripts/test-tls13-minerva.py` line 68 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjrJS-p4un8rNZ22pka:-NjrJS-q2ulxoludWtP0:bwamclg) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/scripts/test-tls13-minerva.py#L68)):*
> ```Python
>     print("                  optional for running timing analysis.")
>     print(" --alpha num      Acceptable probability of a false positive. Default: 1e-6.")
>     print(" --verbose        Print's a more verbose output.")
> ```

nit: the apostrophe isn't needed here
___
*[`scripts/test-tls13-minerva.py` line 408 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NjoM04vCuGvKjDb_Ozw:-NjoM04vCuGvKjDb_Ozx:btb20lj) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/scripts/test-tls13-minerva.py#L408)):*
> ```Python
>                     raw_times=join(timing_outdir, "timing.csv"),
>                     data=join(timing_outdir, data_file),
>                     data_size=32,
> ```

that size should depend sig_alg used, shouldn't it?


<!-- Sent from Reviewable.io -->

2023-12-02 12:01 UTC, tomato42 commented
(just a quick look at the CI failures)

> we probably shouldn't run real packet capture in the tlslite-ng-random-subset.json configuration

by that I meant that the options specified to the script shouldn't cause it to run capture, not for it to be omitted from the `tlslite-ng-random-subset.json`

and 2:
the failures in runs with analysis are relevant:
```
 ======================================================================
ERROR: test_bit_size_measurement_analysis_main_100_samples (tests.test_tlsfuzzer_analysis.TestMeasurementAnalysis.test_bit_size_measurement_analysis_main_100_samples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/tlsfuzzer/tlsfuzzer/tests/test_tlsfuzzer_analysis.py", line 1177, in test_bit_size_measurement_analysis_main_100_samples
    self.analysis.analyze_bit_sizes()
  File "/home/runner/work/tlsfuzzer/tlsfuzzer/tlsfuzzer/analysis.py", line 1703, in analyze_bit_sizes
    if pvalue < (self.alpha / len(k_sizes)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'dotDict' and 'float'
```

2023-12-13 19:21 UTC, tomato42 commented
test-tls13-minerva.py should probably be added to the https://github.com/tlsfuzzer/tlsfuzzer/blob/master/docs/source/timing-analysis.rst

2024-01-08 18:14 UTC, tomato42 commented
Do I read it wrong, or are the confidence intervals for each bit size calculated twice?:
```
...
[i] Wilcoxon signed-rank test done in 10.5s
[i] Calculating confidence intervals of central tendencies
Done: 100.00%, elapsed:  6m 58.66s, speed: 14.78 bootstraps/s, avg speed: 11.94 bootstraps/s, remaining:  0.00s, ETA: 12:59:44 08-01-2024              
[i] Confidence intervals of central tendencies done in 4.2e+02s
Creating graphs for k size 519...
[i] Graphing confidence interval plots
Done: 100.00%, elapsed:  6m 52.65s, speed: 14.93 bootstraps/s, avg speed: 12.12 bootstraps/s, remaining:  0.00s, ETA: 13:06:39 08-01-2024          
[i] Confidence interval plots done in 4.14e+02s
...
```

2024-01-10 14:34 UTC, tomato42 commented
I've noticed that the nonce extraction takes a lot of time, but then one extraction doesn't depend on the other (from signature to signature), and it's fairly computationally intensive, so, couldn't we run it parallel on multiple CPU cores?

2024-01-16 10:42 UTC, GeorgePantelakis commented
For the first comment yes the conf intervals are calculated twice and this is something that needs to be fixed. Also, I like the idea of parallel execution in some independent parts. Do you think it should be done in this PR or we should create another one with optimizations and fixes (since this is for TLS-level test/gatherer)? I personally vote for the latter.

2024-01-16 15:37 UTC, tomato42 requested changes
> Reviewed 1 of 5 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: all files reviewed, 7 unresolved discussions (waiting on @GeorgePantelakis)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuX9er8O9Wppiqv7dd:-NoHtI5m4wQ_CmNeTueW:b-5mgtv9) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

When I run it against tlslite-ng I'm getting an error:
```
[Decimal('1699641567.684276569')]  
[Decimal('1699641567.688228384'), Decimal('1699641567.692023192')]  
Done:   1.06%, elapsed:  0.00s, speed: 3.34MiB/s, avg speed: 3.34MiB/s, remaining:  0.06s, ETA: 19:39:31 10-11-2023       
Traceback (most recent call last):  
 File "/home/hkario/dev/tlsfuzzer/scripts/test-minerva-ecdsa.py", line 449, in <module>
...
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 595, in add_timing  
   self._flush_to_files()  
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 615, in _flush_to_files  
   self._write_pkt_header()  
 File "/home/hkario/dev/tlsfuzzer/tlsfuzzer/extract.py", line 770, in _write_pkt_header  
   raise ValueError("For every client query we need a response "  
ValueError: For every client query we need a response (try FIN as server response)
```

some code missing?
</blockquote></details>

yes, but on tlslite-ng side, we need this merged first: https://github.com/tlsfuzzer/tlslite-ng/pull/506

___
___
*[`tlsfuzzer/expect.py` line 1041 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoHuYN_9OcFJnuXgJ2u:-NoHuYN_9OcFJnuXgJ2v:b-uy97ry) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d275b8a6358c7ee972b884bf229cfe137a82894a/tlsfuzzer/expect.py#L1041)):*
> ```Python
>     """
>     Processing TLS Handshake protocol Certificate Verify messages.
>     :param str version: Expected TLS version of the message. If not provided
> ```

I'm pretty sure that `version` is a `tuple(int,int)` here...
___
*[`tlsfuzzer/expect.py` line 1043 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoHuh1W0opiW3TQRD6l:-NoHuh1X8lylClPhWriV:bbptq2n) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d275b8a6358c7ee972b884bf229cfe137a82894a/tlsfuzzer/expect.py#L1043)):*
> ```Python
>     :param str version: Expected TLS version of the message. If not provided
>     will be taken from the state.
>     :param str sig_alg: Expected value of the signature scheme created by the
> ```

same here, not `str` but `tuple(int,int)`
___
*[`scripts/test-minerva-ecdsa.py` line 85 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NiuVBAT5vGsNkNTaNGK:-NoHtX-eETDW8vqKyg1a:b-hmde9q) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9f8b7ad23e6f76aeec435a0bf8dcfc837b439388/scripts/test-minerva-ecdsa.py#L85)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

having support for `--status-delay=30` and `--status-newline` would be nice or running the script in CI
</blockquote></details>

not fixed
___
*[`scripts/test-tls13-minerva.py` line 48 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoHtZ9n6phOCb3wk81-:-NoHtZ9n6phOCb3wk810:b-grgpdf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/bd47856cb929c0a4abf8ffd68e023df81b7bce3a/scripts/test-tls13-minerva.py#L48)):*
> ```Python
>     print("                  Default is /tmp")
>     print(" -i interface     Recording timing information on specified interface.")
>     print("                  Default is lo (loopback)")
> ```

why drop this?
___
*[`scripts/test-tls13-minerva.py` line 437 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoHtnde5EXsPpaL7LDx:-NoHtnde5EXsPpaL7LDy:b-jhof63) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d275b8a6358c7ee972b884bf229cfe137a82894a/scripts/test-tls13-minerva.py#L437)):*
> ```Python
>                       "Install required packages to enable.")
>     else:
>         print("Skipping data gathering because interface is not defined.")
> ```

maybe "...because network interface is not set" would be more understandable?


<!-- Sent from Reviewable.io -->

2024-01-19 13:19 UTC, tomato42 requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: all files reviewed, 12 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`docs/source/timing-analysis.rst` line 31 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWoK2q-lDiDTGSDrey:-NoWoK2q-lDiDTGSDrez:b-giindm) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L31)):*
> ```reStructuredText
> in ECDSA signing process based on the size of the nonce to get the private key.
> You can test for it using the `test-tls13-minerva.py
> <https://github.com/tomato42/tlsfuzzer/blob/master/scripts/test-tls13-minerva.py>`_
> ```

that's the old URL, we shouldn't keep adding references to it, use the github.com/tlsfuzzer/tlsfuzzer URL instead
___
*[`docs/source/timing-analysis.rst` line 205 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWohDDD6BxjIyElVBN:-NoWohDDD6BxjIyElVBO:bhzwhl3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L205)):*
> ```reStructuredText
> observations differ significantly or not.
> 
> In frequentest statistics tests work in terms of hypothesis testing.
> ```

good catch on the `statistics` but `frequentist` was correct: https://en.wikipedia.org/wiki/Frequentist_inference
___
*[`docs/source/timing-analysis.rst` line 267 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWp7GPCD-jUL1FCp54:-NoWp7GPCD-jUL1FCp55:b-nrnjwq) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L267)):*
> ```reStructuredText
> Or execute the same script with the same settings 100 times, combine
> the resulting data in ``timing.csv`` files or ``measurements.csv`` files for
> Minerva/bit-size and analyse such combined data set.
> ```

that aside should be added in parentheses, otherwise the Minerva part is rather hard to parse/confusing

also, what about measurements-inverse.csv?
___
*[`docs/source/timing-analysis.rst` line 394 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWplwv9jAcLUaYD_hw:-NoWplwv9jAcLUaYD_hx:bdyw5f6) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L394)):*
> ```reStructuredText
> In case you want to run the extraction on another machine you can do this by
> providing the raw times, the data, the signatures, the private key and specify
> the ``--prehashed`` flag:
> ```

I would add a `.. note::` here explaining that different key sizes will require use of different data sizes (and also explain why 32, that it's the size of sha-256 output)
___
*[`docs/source/timing-analysis.rst` line 402 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWpzVF9V6u3CsK6jEM:-NoWpzVF9V6u3CsK6jEN:b-5h3av2) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L402)):*
> ```reStructuredText
>    --priv-key-ecdsa priv_key.pem -o /tmp/results/ --prehashed
> 
> This will create a ``measurements.csv`` file with the measurements in a long
> ```

s/in a long/in the long/ ?
___
*[`docs/source/timing-analysis.rst` line 585 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWqWFoDIT2IIqUfl28:-NoWqWFoDIT2IIqUfl29:bymkjej) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L585)):*
> ```reStructuredText
> 
> For Minerva attack and similar bit-size attacks we also create plots with all
> the nonces componined to have a more complete view of the potential side
> ```

"componined"? you meant compared? also, shouldn't that be "nonce sizes" not nonces themselves
___
*[`docs/source/timing-analysis.rst` line 589 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWr-UU3iHkoliAQtm_:-NoWr-UU3iHkoliAQtma:b-rkx62s) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L589)):*
> ```reStructuredText
> during the analysis. The plots can be found under the names
> ``conf_interval_plot_all_k_sizes_*.png`` and they are split to have at most 10
> nonces at a time. Plots for individual nonces can be found under the
> ```

nonce sizes
___
*[`docs/source/timing-analysis.rst` line 673 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWrACx0O6fJjDTtEqo:-NoWrACx0O6fJjDTtEqp:bpzu81t) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L673)):*
> ```reStructuredText
> samples for a given sample size.
> 
> For minerva and bit size attacks there is no ``report.txt`` file. Fillany a
> ```

Finally?
___
*[`docs/source/timing-analysis.rst` line 676 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWrE0m3x_Ufe7D-k5e:-NoWrE0m3x_Ufe7D-k5f:b-lsvcco) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L676)):*
> ```reStructuredText
> ``bootstrap_test.results`` file is created for the bootstrap results for each
> nonce size. If some nonce has very small (typically <0.00001) p-value or
> wilcoxon value (found in respecive files) and the confidence intervals of the
> ```

it should be Wilcoxon, as that's a surname
___
*[`docs/source/timing-analysis.rst` line 678 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoWrMdD64Tq8J5MniiW:-NoWrMdD64Tq8J5MniiX:b-3f6gd7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/161c8dca160e06bd1839c2bd0c8406d5f867df40/docs/source/timing-analysis.rst#L678)):*
> ```reStructuredText
> wilcoxon value (found in respecive files) and the confidence intervals of the
> bootstrap test is also small (typically <1ns) for the specific nonce, then a
> side channel is present.
> ```

no, you can have large confidence interval and small p-values. We need to look at p-value and at the CI only to show _absence_ of a side-channel; presence of a side-channel is determined by p-values alone


<!-- Sent from Reviewable.io -->

2024-01-19 16:27 UTC, tomato42 requested changes
OK, added to #901 

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-:-NoXWwrP3nxKtgmes8LP:b-1vumxz)* status: all files reviewed, 4 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`docs/source/timing-analysis.rst` line 684 at r7](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoXXoWZ8X2lJP2Zalwd:-NoXXoWZ8X2lJP2Zalwe:buifzys) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/da20b0eae7c5899d754876ba0e58e71be887d72e/docs/source/timing-analysis.rst#L684)):*
> ```reStructuredText
> ``bootstrap_test.results`` file is created for the bootstrap results for each
> nonce size. If some nonce size has large (typically >0.01) p-value or
> Wilcoxon value (found in respecive files) and the confidence intervals of the
> ```

sign test p-value or Wilcoxon test p-value
___
*[`docs/source/timing-analysis.rst` line 686 at r7](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoXXX4C6SlpEMahyU8B:-NoXXX4C6SlpEMahyU8C:bim49eo) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/da20b0eae7c5899d754876ba0e58e71be887d72e/docs/source/timing-analysis.rst#L686)):*
> ```reStructuredText
> Wilcoxon value (found in respecive files) and the confidence intervals of the
> bootstrap test is small (typically <1ns) for the specific nonce size, then
> we can confirm that no side-channel is present for this nonce size eitherwise
> ```

s/eitherwise/otherwise/
___
*[`docs/source/timing-analysis.rst` line 687 at r7](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoXXaRj-RdMkG2e7_93:-NoXXaRj-RdMkG2e7_94:b7fgg7l) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/da20b0eae7c5899d754876ba0e58e71be887d72e/docs/source/timing-analysis.rst#L687)):*
> ```reStructuredText
> bootstrap test is small (typically <1ns) for the specific nonce size, then
> we can confirm that no side-channel is present for this nonce size eitherwise
> if we have very small p-value or Wilcoxon value (typically <0.00001) then a
> ```

...small sign test p-value or Wilcoxon test p-value
___
*[`docs/source/timing-analysis.rst` line 688 at r7](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885#-NoXXgzD1Fhb8Wt8vQDR:-NoXXgzD1Fhb8Wt8vQDS:b8zktbb) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/da20b0eae7c5899d754876ba0e58e71be887d72e/docs/source/timing-analysis.rst#L688)):*
> ```reStructuredText
> we can confirm that no side-channel is present for this nonce size eitherwise
> if we have very small p-value or Wilcoxon value (typically <0.00001) then a
> side-channel is present on for this nonce size.
> ```

is present for this nonce size


<!-- Sent from Reviewable.io -->

2024-01-19 16:57 UTC, tomato42 approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-01-19 17:06 UTC, merged

2024-01-19 17:06 UTC, tomato42 commented
Thank you!

2026-08-20 10:39 UTC, XinGOfCloude18 approved these changes

2026-08-20 10:40 UTC, XinGOfCloude18 commented
> test-tls13-minerva.py should probably be added to the https://github.com/tlsfuzzer/tlsfuzzer/blob/master/docs/source/timing-analysis.rst

2026-08-20 10:40 UTC, XinGOfCloude18 commented
> Do I read it wrong, or are the confidence intervals for each bit size calculated twice?:
> ```
> ...
> [i] Wilcoxon signed-rank test done in 10.5s
> [i] Calculating confidence intervals of central tendencies
> Done: 100.00%, elapsed:  6m 58.66s, speed: 14.78 bootstraps/s, avg speed: 11.94 bootstraps/s, remaining:  0.00s, ETA: 12:59:44 08-01-2024              
> [i] Confidence intervals of central tendencies done in 4.2e+02s
> Creating graphs for k size 519...
> [i] Graphing confidence interval plots
> Done: 100.00%, elapsed:  6m 52.65s, speed: 14.93 bootstraps/s, avg speed: 12.12 bootstraps/s, remaining:  0.00s, ETA: 13:06:39 08-01-2024          
> [i] Confidence interval plots done in 4.14e+02s
> ...
> ```