tlsfuzzer/analysis.py: create bit size report.txt
tlsfuzzer/tlsfuzzer pull request #911
Opened 2024-02-22 16:25 UTC by GeorgePantelakis

### Description
Updated code to generate a report.txt, similar to what the regular analysis does, including average, max, and min p-values, the result of the Skillings-Mack test, statistics for the 10 biggest k-values, and layperson explanation of the result.

### Motivation and Context
Easier understanding of bit size analysis results.

### Checklist

- [ ] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)

2024-03-01 15:34 UTC, tomato42 requested changes
can you also provide example report.txt contents?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-:-Nrudce2A44zZG7MA0BS:b-sihve5)* status: all files reviewed, 4 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 1551 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruUFDC64cZq4jjpSFV:-NruUFDC64cZq4jjpSFW:b-v2xmwr) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1551)):*
> ```Python
>             try:
>                 sm_test = skillings_mack_test(values, groups, blocks,
>                                               # XXX
> ```

why XXX?, if it's in relation to the `first`, then the comment should be more like "because the blocks are sorted, and the first instance of the biggest k is the base value, while the second instance is the sanity check, in case of duplicates we want to use first value"
___
*[`tlsfuzzer/analysis.py` line 1589 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruXWeo9Vg_BFB4BkIn:-NruXWeo9Vg_BFB4BkIo:b-barq0c) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1589)):*
> ```Python
>             for k_size in top_k_sizes:
>                 bootstraping_of_size = self._bit_size_bootstraping[k_size]
>                 for method in bootstraping_of_size:
> ```

shouldn't this be `larger_ci = max(bootstrapping_of_size[method][1] for method in bootstrapping_of_size)`?
___
*[`tlsfuzzer/analysis.py` line 1619 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruY9cl7O0GYKPak1tf:-NruY9cl7O0GYKPak1tg:b-ckj3if) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1619)):*
> ```Python
>         with open(join(self.output, "report.txt"), "w") as fp:
>             fp.write(
>                 "Skilling-Mack test p-value: {0:.2e}\n"
> ```

since this will be logged and saved for later, it will be better to have a more precise value for the later analysis of uniformity of multiple runs. like at least 4, if not 6, digits after the comma
___
*[`tlsfuzzer/analysis.py` line 1687 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruX6ZBAUNIIpIFDlNF:-NruX6ZBAUNIIpIFDlNG:bz2q6l) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1687)):*
> ```Python
>         """
>         if bit_size:
>             self.skillings_mack_pvalue = self.skillings_mack_test()
> ```

this really shouldn't be an instance variable...


<!-- Sent from Reviewable.io -->

2024-03-01 17:15 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 1551 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruUFDC64cZq4jjpSFV:-Nrv-V8e--BifYkD8RT6:bhbjlv7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1551)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why XXX?, if it's in relation to the `first`, then the comment should be more like "because the blocks are sorted, and the first instance of the biggest k is the base value, while the second instance is the sanity check, in case of duplicates we want to use first value"
</blockquote></details>

This XXX was there in your code so I didn't know what to replace it so I left it there. Now it has been replaced by the comment you sent. 
___
*[`tlsfuzzer/analysis.py` line 1589 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruXWeo9Vg_BFB4BkIn:-Nrv-qlgCFvqFBgahRi4:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1589)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

shouldn't this be `larger_ci = max(bootstrapping_of_size[method][1] for method in bootstrapping_of_size)`?
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1619 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruY9cl7O0GYKPak1tf:-Nrv-r8Z48c_Wj0qZ1M6:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1619)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

since this will be logged and saved for later, it will be better to have a more precise value for the later analysis of uniformity of multiple runs. like at least 4, if not 6, digits after the comma
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1687 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruX6ZBAUNIIpIFDlNF:-Nrv-rwi9tFLQT6I6ey4:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1687)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this really shouldn't be an instance variable...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-01 17:20 UTC, GeorgePantelakis commented
Example of report.txt file after analysis:

```
Skilling-Mack test p-value: 2.379562e-01
Sign test p-values (min, average, max): 1.21e-01, 5.45e-01, 1.00e+00
Wilcoxon test p-values (min, average, max): 2.34e-02, 5.74e-01, 1.00e+00
Large confidence intervals detected, collecting more data necessary. Side channel leakage smaller than 3.226e-07s is possible.

----------------------------------------------------------------------------------------
| size | Sign test | Wilcoxon test |    Trimmed mean (5%)    |    Trimmed mean (45%)   |
|  256 |  8.67e-01 |    7.91e-01   |  5.132e-08 (±3.11e-07s) | -4.124e-09 (±8.60e-08s) |
|  255 |  9.62e-01 |    4.54e-01   |  3.442e-08 (±1.50e-07s) | -5.127e-10 (±3.84e-08s) |
|  254 |  4.07e-01 |    7.63e-01   |  2.660e-08 (±1.89e-07s) | -1.090e-08 (±4.95e-08s) |
|  253 |  1.31e-01 |    5.62e-02   |  1.123e-07 (±2.64e-07s) |  2.729e-08 (±6.52e-08s) |
|  252 |  1.21e-01 |    5.33e-01   |  1.514e-08 (±3.23e-07s) | -3.493e-08 (±1.02e-07s) |
|  251 |  4.55e-01 |    5.45e-01   |  2.952e-08 (±4.39e-07s) |  2.340e-08 (±1.15e-07s) |
|  250 |  1.00e+00 |    9.37e-01   | -8.220e-08 (±6.73e-07s) | -9.967e-09 (±1.82e-07s) |
|  249 |  2.45e-01 |    2.36e-01   |  1.291e-07 (±8.20e-07s) |  8.550e-08 (±2.71e-07s) |
|  248 |  4.45e-01 |    5.48e-01   | -2.167e-07 (±1.24e-06s) | -8.799e-08 (±4.02e-07s) |
|  247 |  2.46e-01 |    6.42e-01   | -1.834e-07 (±1.60e-06s) | -8.551e-08 (±3.60e-07s) |
----------------------------------------------------------------------------------------
```

2024-03-01 17:48 UTC, tomato42 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911)* status: all files reviewed, 1 unresolved discussion (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 1551 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-NruUFDC64cZq4jjpSFV:-Nrv5mcfC8ul-wjYdwlj:b-m9h7tt) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/87101033ae1f1f2fe7e1d9a91f4b2df77fc1eebe/tlsfuzzer/analysis.py#L1551)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

This XXX was there in your code so I didn't know what to replace it so I left it there. Now it has been replaced by the comment you sent.
</blockquote></details>

aah, it's there because it's needed for bit-size analysis but shouldn't be necessary for Hamming weight analysis (and there it will provide a sanity check on data)
___
*[`tlsfuzzer/analysis.py` line 1599 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-Nrv6FKU40K5gt-JQLg6:-Nrv6FKU40K5gt-JQLg7:b-t6jiyh) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/3ce96181b0d894285bd63709287af5b7becca31b/tlsfuzzer/analysis.py#L1599)):*
> ```Python
>                     bootstrapping_of_size[method][1]
>                     for method in bootstrapping_of_size
>                 )
> ```

no, actually that's not right: it will ignore the first 4 values from top_k_sizes,
so it should be rather something like
```
                larger_ci = max(
                    self._bit_size_bootstrapping[k_size][method][1]
                    for method in self._bit_size_bootstrapping[k_size]
                    for k_size in top_k_sizes
                )
```


<!-- Sent from Reviewable.io -->

2024-03-04 17:09 UTC, tomato42 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/911#-:-Ns9RABm247tfZsrtVqx:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-03-04 17:09 UTC, merged

2024-03-04 17:09 UTC, tomato42 commented
thanks!