tlsfuzzer/analysis.py: report for Hamming weight and more
tlsfuzzer/tlsfuzzer pull request #920
Opened 2024-04-05 16:24 UTC by GeorgePantelakis

### Description
1) Created experimental report txt file for Hamming weight analysis 
2) Fix reporting wrong data used in bit analysis report.txt 
3) Added script version to reports
4) Printing according to verbose on Hamming weight analysis 
5) Changed smart analysis to take into account all the k-sizes up to the desired one.
6) Added 10ns side channel sanity to Hamming weight analysis

### Motivation and Context
Various improvements and fixes

### Checklist
- [ ] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] all new and existing tests pass (see CI results)

2024-04-09 11:11 UTC, tomato42 commented
Just looking at coverage, it looks to me like we need more unit tests...

2024-04-12 17:03 UTC, tomato42 commented
The goal isn't "over 90%", it's "doesn't decrease too much", and in the recent merges we've had coverage decreasing regularly.

In particular, in this PR, there are 5 branches in `analysis.py` which are covered and 15 which are not.

For reading, you need to go to the report linked from `coverage/coveralls` job, or click any Coveralls job and go one level up in hierarchy, to see coverage for the whole build, not a single run (https://coveralls.io/builds/66747487) in this case

2024-05-02 20:13 UTC, tomato42 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920)* status: all files reviewed, 2 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 2133 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-Nwutjut7_ARYx9t7s-K:-Nwutjut7_ARYx9t7s-L:b-xwrerb) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2133)):*
> ```Python
>                 old_output, "analysis_results/k-by-size/{0}".format(k_size))
> 
>             recognition_results = self.calc_diff_conf_int(pair)
> ```

what ensures that we're using a random subset of measurements? or this does not address #921?
___
*[`tlsfuzzer/analysis.py` line 2143 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-NwuujdsDYKr7mko-WOt:-NwuujdsDYKr7mko-WOu:b-wx4oqt) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2143)):*
> ```Python
>                 print("[W] There is not enough data on recognition size to " +
>                       "calculate desired sample size. " +
>                       "Using all available samples.")
> ```

do we now include in report.txt that smart analysis was active?


<!-- Sent from Reviewable.io -->

2024-05-03 09:05 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 2133 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-Nwutjut7_ARYx9t7s-K:-Nwxfr7M8BUGWnWGMLSh:bdyev1w) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2133)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

what ensures that we're using a random subset of measurements? or this does not address #921?
</blockquote></details>

The randomness is happening in the load_data function with the start variable not here. It is supposed to address the issue. 
___
*[`tlsfuzzer/analysis.py` line 2143 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-NwuujdsDYKr7mko-WOt:-NwxgWWc8IF81pmxZiWH:b-ld0k44) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2143)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

do we now include in report.txt that smart analysis was active?
</blockquote></details>

Not sure I get the question. Probably it is not explicitly mentioned somewhere but there is a line in the report.txt that we used X samples.


<!-- Sent from Reviewable.io -->

2024-05-03 09:19 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 2133 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-Nwutjut7_ARYx9t7s-K:-NwxjnW09kXypIdhSycW:b-hmwdi3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2133)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

The randomness is happening in the load_data function with the start variable not here. It is supposed to address the issue.
</blockquote></details>

Now that I look at it, it is not really solving the issue but there will be another PR that will address all the points of the issue. There will be big changes in the way smart analysis works.


<!-- Sent from Reviewable.io -->

2024-05-03 13:04 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920)* status: all files reviewed, 1 unresolved discussion (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 2133 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-Nwutjut7_ARYx9t7s-K:-NwyYBaM8YPH2Y1MIHLP:b-dsf11u) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2133)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Now that I look at it, it is not really solving the issue but there will be another PR that will address all the points of the issue. There will be big changes in the way smart analysis works.
</blockquote></details>

OK, so we haven't reached the destination but we're moving in the correct direction, good enough for me for now
___
*[`tlsfuzzer/analysis.py` line 2143 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/920#-NwuujdsDYKr7mko-WOt:-NwyYN9r5N2q2ZyxRVqc:bk4bb8a) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/43f36735e7712b059c0a7bd792c18f71bbba678c/tlsfuzzer/analysis.py#L2143)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Not sure I get the question. Probably it is not explicitly mentioned somewhere but there is a line in the report.txt that we used X samples.
</blockquote></details>

can we make it `... used X samples out of Y available`?


<!-- Sent from Reviewable.io -->

2024-05-04 18:41 UTC, tomato42 approved these changes

2024-05-04 18:41 UTC, merged

2024-05-04 18:41 UTC, tomato42 commented
thank you!